name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --windowed --name touch_test touch_test.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: touch_test_exe
          path: dist/touch_test.exe
